// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnb7NO72S2RNnjZcqCbGKRlP5E_pH05wI',
    appId: '1:840194869259:web:eff6d29fe71bcf160a1f0e',
    messagingSenderId: '840194869259',
    projectId: 'chief-24f12',
    authDomain: 'chief-24f12.firebaseapp.com',
    storageBucket: 'chief-24f12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzPSWQoMd5-W3jz58yGpRqqoqSypAUCag',
    appId: '1:840194869259:android:638051a1ba0a42fa0a1f0e',
    messagingSenderId: '840194869259',
    projectId: 'chief-24f12',
    storageBucket: 'chief-24f12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtONtWJc3fD2ciuN4ZPV9u6Zd4WHX2v8Y',
    appId: '1:840194869259:ios:3fc134f04d57e7c80a1f0e',
    messagingSenderId: '840194869259',
    projectId: 'chief-24f12',
    storageBucket: 'chief-24f12.appspot.com',
    iosBundleId: 'com.example.chief',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtONtWJc3fD2ciuN4ZPV9u6Zd4WHX2v8Y',
    appId: '1:840194869259:ios:3fc134f04d57e7c80a1f0e',
    messagingSenderId: '840194869259',
    projectId: 'chief-24f12',
    storageBucket: 'chief-24f12.appspot.com',
    iosBundleId: 'com.example.chief',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnb7NO72S2RNnjZcqCbGKRlP5E_pH05wI',
    appId: '1:840194869259:web:ccbcfa198f02e5a40a1f0e',
    messagingSenderId: '840194869259',
    projectId: 'chief-24f12',
    authDomain: 'chief-24f12.firebaseapp.com',
    storageBucket: 'chief-24f12.appspot.com',
  );

}