// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEbdlH3FpvkaXzDshsToSZ_Z7k0p95j5c',
    appId: '1:231264327549:web:28dd18190a5d595cf0de14',
    messagingSenderId: '231264327549',
    projectId: 'booking-bab28',
    authDomain: 'booking-bab28.firebaseapp.com',
    storageBucket: 'booking-bab28.firebasestorage.app',
    measurementId: 'G-PZX9Z7YFYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0oU00gjGXfMJDDMjanNOfSKMx94WHc5s',
    appId: '1:231264327549:android:3fc4dd074223ffc1f0de14',
    messagingSenderId: '231264327549',
    projectId: 'booking-bab28',
    storageBucket: 'booking-bab28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9aEjxu2kfOgi0tDukmGm2zCSNXsLQyzI',
    appId: '1:231264327549:ios:2d8f01c00d29aad4f0de14',
    messagingSenderId: '231264327549',
    projectId: 'booking-bab28',
    storageBucket: 'booking-bab28.firebasestorage.app',
    iosBundleId: 'com.example.chief',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9aEjxu2kfOgi0tDukmGm2zCSNXsLQyzI',
    appId: '1:231264327549:ios:2d8f01c00d29aad4f0de14',
    messagingSenderId: '231264327549',
    projectId: 'booking-bab28',
    storageBucket: 'booking-bab28.firebasestorage.app',
    iosBundleId: 'com.example.chief',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEbdlH3FpvkaXzDshsToSZ_Z7k0p95j5c',
    appId: '1:231264327549:web:44a3389d68c9453af0de14',
    messagingSenderId: '231264327549',
    projectId: 'booking-bab28',
    authDomain: 'booking-bab28.firebaseapp.com',
    storageBucket: 'booking-bab28.firebasestorage.app',
    measurementId: 'G-WBNPKK6T7L',
  );
}
